version: "3.5"
services:

  mongodb:
    container_name: orion-mongodb
    image: mongo:5.0.6
    restart: unless-stopped
    environment:
       - MONGO_DATA_DIR=/data/db
       - MONGO_LOG_DIR=/dev/null
       - "TZ=America/Detroit"
    volumes:
       - "${ENV_MONGO_DATA_MOUNT}:/data/db"
       - "${ENV_DATALAKE_FILE_DIR}:/data"
    ports:
      - "127.0.0.1:${ENV_MONGO_PORT:-27017}:27017"
    command: mongod
    networks:
      dataLake:
        aliases:
          - mongodb    

  spring:
    container_name: orion-spring
    image:  ${ENV_SPRING_IMAGE}
    restart: unless-stopped
    depends_on: 
      - mongodb
    ports:
      - 3030
    volumes:
      - "${ENV_GLOBUS_FILE_MOUNT}:/globus"      
      - "${ENV_GLOBUS_TOKEN_LOCATION}:/globus_tokens"
    environment:
      GLOBUS_API_KEY: ${ENV_GLOBUS_API_KEY}
      GLOBUS_API_SECRET: ${ENV_GLOBUS_API_SECRET}      
      CLIENT_ID: ${ENV_CLIENT_ID}
      GLOBUS_DIR: ${ENV_GLOBUS_DIR}
      TZ: "America/Detroit"
    privileged: true
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "${ENV_FLUENTD_ADDRESS}"
        tag: "orion-data"
    networks:
      dataLake:
        aliases:
          - spring

  user-auth:
    container_name: user-auth
    image: ${ENV_USER_AUTH_IMAGE}
    restart: unless-stopped
    environment:
      DEFAULT_CLIENT_ID: ${ENV_DEFAULT_CLIENT_ID}
      TZ: "America/Detroit"
    privileged: true
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "${ENV_FLUENTD_ADDRESS}"
        tag: "orion-data"
    networks:
      dataLake:
        aliases:
          - user-auth

volumes:
  esdata:

networks:
  dataLake:
    external: true
