version: "3.5"
services:

  mongodb:
    container_name: mongodb
    image: mongo:4.0
    restart: unless-stopped
    environment:
       - MONGO_DATA_DIR=/data/db
       - MONGO_LOG_DIR=/dev/null
       - "TZ=America/Detroit"
    volumes:
       - mongodbdata:/data/db 
    ports:
      - "127.0.0.1:${ENV_MONGO_PORT:-27017}:27017"
    command: mongod
    networks:
      dataLake:
        aliases:
          - mongodb    

  spring:
    container_name: spring
    image: kingstonduo/kpmp-spring
    restart: unless-stopped
    depends_on: 
      - mongodb
    ports:
      - 3030
    volumes:
      - "${ENV_SPRING_BOOT_APPDIR}:/home/gradle"
      - "${ENV_DATALAKE_FILE_DIR}:/data"
      - "${ENV_WORKER_LOCATION}:/home/gradle/zipWorker"
      - "${ENV_GLOBUS_FILE_MOUNT}:/globus"      
    environment:
      SPRING_BOOT_ENVIRONMENT: ${ENV_DOCKER_ENVIRONMENT}
      GLOBUS_API_KEY: ${ENV_GLOBUS_API_KEY}
      GLOBUS_API_SECRET: ${ENV_GLOBUS_API_SECRET}      
      CLIENT_ID: ${ENV_CLIENT_ID}
      GLOBUS_DIR: ${ENV_GLOBUS_DIR}
      TZ: "America/Detroit"
    privileged: true
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "${ENV_FLUENTD_ADDRESS}"
        tag: "orion-data"
    networks:
      dataLake:
        aliases:
          - spring

  user-auth:
    container_name: user-auth
    image: kingstonduo/user-auth:1.1
    restart: unless-stopped
    environment:
      DEFAULT_CLIENT_ID: ${ENV_DEFAULT_CLIENT_ID}
      TZ: "America/Detroit"
    privileged: true
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "${ENV_FLUENTD_ADDRESS}"
        tag: "orion-data"
    networks:
      dataLake:
        aliases:
          - user-auth

volumes:
  esdata:
  mongodbdata:

networks:
  dataLake:
    external: true
