version: "3.5"
services:

  mongodb:
    container_name: mongodb
    image: mongo:4.0
    environment:
       - MONGO_DATA_DIR=/data/db
       - MONGO_LOG_DIR=/dev/null
    volumes:
       - mongodbdata:/data/db 
    ports:
      - "127.0.0.1:${ENV_MONGO_PORT:-27017}:27017"
    command: mongod 
    networks:
      dataLake:
        aliases:
          - mongodb

  spring:
    container_name: spring
    image: kingstonduo/kpmp-spring
    ports:
      - "${ENV_APACHE_TOMCAT_PORT:-3030}:3030"
    volumes:
      - "${ENV_SPRING_BOOT_APPDIR}:/home/gradle"
      - "${ENV_DATALAKE_FILE_DIR}:/data"
      - "${ENV_WORKER_LOCATION}:/home/gradle/zipWorker"
    environment:
      SPRING_BOOT_ENVIRONMENT: ${ENV_DOCKER_ENVIRONMENT}
    privileged: true
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "localhost:24224"
        tag: "orion-data"
    networks:
      dataLake:
        aliases:
          - spring

  user-auth:
    container_name: user-auth
    image: kingstonduo/user-auth:1.0
    environment:
      DEFAULT_CLIENT_ID: ${ENV_DEFAULT_CLIENT_ID}
    privileged: true
    networks:
      local:
        aliases:
          - user-auth

volumes:
  esdata:
  mongodbdata:

networks:
  dataLake:
    external: true
