version: "3.5"
services:

  apache:
    container_name: orion-apache
    image: ${ENV_APACHE_CONTAINER} 
    ports:
      - "80:80"
      - "443:443"
    environment:
      - "TZ=America/Detroit"
      - ENV_APACHE_SERVER_NAME=${ENV_APACHE_SERVER_NAME}
    volumes:
      - ${ENV_REACT_APPDIR}/build:/var/www/html
      - ${ENV_SSL_CERT_DIR}:/certs
      - ${ENV_SHIB_CONF_DIR}/shibboleth2.xml:/etc/shibboleth/shibboleth2.xml
    networks:
      local:
        aliases:
          - apache

  mongodb:
    container_name: orion-mongodb
    image: arm64v8/mongo:5.0
    platform: linux/arm64/v8
    environment:
       - MONGO_DATA_DIR=/Users/rlreamy/data/db
       - MONGO_LOG_DIR=/dev/null
       - "TZ=America/Detroit"
    volumes:
       - mongodbdata:/Users/rlreamy/data/db 
    ports:
      - "127.0.0.1:${ENV_MONGO_PORT:-27017}:27017"
    command: mongod 
    networks:
      local:
        aliases:
          - mongodb

  spring:
    container_name: orion-spring
    image: ${ENV_SPRING_IMAGE} 
    ports:
      - "${ENV_APACHE_TOMCAT_PORT:-3030}:3030"
    volumes:
      - "${ENV_GLOBUS_FILE_MOUNT}:/globus"
    environment:
      - GLOBUS_API_KEY=${ENV_GLOBUS_API_KEY}
      - GLOBUS_API_SECRET=${ENV_GLOBUS_API_SECRET}
      - CLIENT_ID=${ENV_CLIENT_ID}
      - GLOBUS_DIR=${ENV_GLOBUS_DIR}
      - "TZ=America/Detroit"
    privileged: true
    networks:
      local:
        aliases:
          - spring

  user-auth:
    container_name: user-auth
    image: kingstonduo/user-auth:2.0
    environment:
      DEFAULT_CLIENT_ID: ${ENV_DEFAULT_CLIENT_ID}
      TZ: "America/Detroit"
    privileged: true
    networks:
      local:
        aliases:
          - user-auth

volumes:
  esdata:
  mongodbdata:

networks:
  local:
    name: dataLake
    ipam:
      driver: default
      config:
        - 
          subnet: 10.252.0.0/16
