version: "3.5"
services:

  mongodb:
    container_name: mongodb
    image: mongo:4.0
    environment:
       - MONGO_DATA_DIR=/data/db
       - MONGO_LOG_DIR=/dev/null
       - "TZ=America/Detroit"
    volumes:
       - mongodbdata:/data/db 
    ports:
      - "127.0.0.1:${ENV_MONGO_PORT:-27017}:27017"
    command: mongod 
    networks:
      dataLake:
        aliases:
          - mongodb

  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${ENV_MARIADB_ROOT_PWD}
    volumes:
      - mariadbdata:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      dataLake:
        aliases:
          - mariadb

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      dataLake:
        aliases:
          - adminer        

  spring:
    container_name: spring
    image: kingstonduo/kpmp-spring
    depends_on: 
      - mongodb
    ports:
      - "${ENV_APACHE_TOMCAT_PORT:-3030}:3030"
    volumes:
      - "${ENV_SPRING_BOOT_APPDIR}:/home/gradle"
      - "${ENV_DATALAKE_FILE_DIR}:/data"
      - "${ENV_WORKER_LOCATION}:/home/pathadmin/apps/zipWorker/build/libs"
      - "${ENV_GLOBUS_FILE_MOUNT}:/globus"      
    environment:
      SPRING_BOOT_ENVIRONMENT: ${ENV_DOCKER_ENVIRONMENT}
      GLOBUS_API_KEY: ${ENV_GLOBUS_API_KEY}
      GLOBUS_API_SECRET: ${ENV_GLOBUS_API_SECRET}      
      CLIENT_ID: ${ENV_CLIENT_ID}
      GLOBUS_DIR: ${ENV_GLOBUS_DIR}
      TZ: "America/Detroit"
    privileged: true
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "${ENV_FLUENTD_ADDRESS}"
        tag: "orion-data"
    networks:
      dataLake:
        aliases:
          - spring

  user-auth:
    container_name: user-auth
    image: kingstonduo/user-auth:1.1
    environment:
      DEFAULT_CLIENT_ID: ${ENV_DEFAULT_CLIENT_ID}
      TZ: "America/Detroit"
    privileged: true
    networks:
      dataLake:
        aliases:
          - user-auth

volumes:
  esdata:
  mongodbdata:
  mariadbdata:

networks:
  dataLake:
    external: true
