version: "3"
services:

  spring:
    build: ./spring
    ports:
      - "${ENV_APACHE_TOMCAT_PORT:-3030}:3030"
    volumes:
      - "${ENV_SPRING_BOOT_APPDIR}:/home/gradle"
      - "${ENV_DATALAKE_FILE_DIR}:/data"
    environment:
      SPRING_BOOT_ENVIRONMENT: ${ENV_DOCKER_ENVIRONMENT}
    networks:
      local:
        aliases:
          - spring

  mysql:
    image: mariadb
    ports: 
      - "${ENV_MYSQL_PORT:-3306}:3306"
    volumes:
      - "mysqldb:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=N32R2sWW2bsbMG75
      - MYSQL_DATABASE=orion
    networks:
      local:
        aliases:
          - mysql
  
  node:
    build: ./node
    working_dir: /home/node
    entrypoint: ["/home/node/scripts/init.sh"]
    ports: 
      - "${ENV_REACT_DEV_SERVER_PORT:-80}:80"
    volumes:
      - ${ENV_REACT_APPDIR}:/home/node
    command: ["npm", "run-script"]
    restart: always
    environment:
      NODE_ENV: ${ENV_DOCKER_ENVIRONMENT:-local}
    networks:
      local:
        aliases:
          - node

  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.4
    ports: 
      - "5601:5601"
    environment:
      SERVER_NAME: elasticsearch
      ELASTICSEARCH_URL: http://elasticsearch:9200
    networks:
      local:
        aliases:
          - kibana
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: "single-node"
    networks:
      local:
        aliases:
          - elasticsearch


volumes:
  mysqldb:

networks:
  local:
    driver: bridge
    ipam:
      driver: default
      config:
        - 
          subnet: 10.252.0.0/16
