version: "3"
services:

  spring:
    image: kpmp/orion-gradle
    ports:
      - "${ENV_APACHE_TOMCAT_PORT:-3030}:3030"
    volumes:
      - "${ENV_SPRING_BOOT_APPDIR}:/home/gradle"
    environment:
      SPRING_BOOT_ENVIRONMENT: ${ENV_SPRING_BOOT_ENVIRONMENT}
    networks:
      local:
        aliases:
          - spring

  mysql:
    image: mariadb
    ports: 
      - "${ENV_MYSQL_PORT:-3306}:3306"
    volumes:
      - "mysqldb:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=N32R2sWW2bsbMG75
      - MYSQL_DATABASE=orion
    networks:
      local:
        aliases:
          - mysql

  # npm:
  #   image: node:carbon
  #   working_dir: /home/node
  #   volumes:
  #     - "${ENV_NPM_PROJECT_DIR}:/home/node"
  #   command: ["npm", "start"]
  #   networks:
  #     local:

volumes:
  mysqldb:

networks:
  local:
    driver: bridge
    ipam:
      driver: default
      config:
        - 
          subnet: 10.252.0.0/16
