version: "3"
services:

  apache:
    container_name: apache
    build:  
      context: ${ENV_APACHE_TARGET}
      args:
        - ENV_APACHE_SERVER_NAME=${ENV_APACHE_SERVER_NAME}
    ports: 
      - "80:80"
      - "443:443"
    volumes:
      - ${ENV_REACT_APPDIR}/build:/var/www/html
