version: "3.5"
services:

  elastalert:
    container_name: elastalert
    image: kingstonduo/elastalert
    volumes:
      - ${ENV_ELASTALERT_CONF}:/opt/elastalert/config.yaml
      - ${ENV_ELASTALERT_TEST_CONF}:/opt/elastalert/config-test.yaml
      - ${ENV_ELASTALERT_SERVER_CONF}:/opt/elastalert-server/config/config.json
      - ${ENV_ELASTALERT_RULES_DIR}:/opt/elastalert/rules
      - ${ENV_ELASTALERT_RULES_TEMPLATE_DIR}:/opt/elastalert/rule_templates
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      logAggregator:
        aliases:
          - elastalert

networks:
  logAggregator:
    external: true