version: "3"
services:

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.0.1
    depends_on: 
      - elasticsearch
    ports: 
      - "5601:5601"
    volumes:
      - ${ENV_KIBANA_CONF_DIR}/kibana.yml:/usr/share/kibana/kibana.yml
    environment:
      SERVER_NAME: elasticsearch
      ELASTICSEARCH_URL: http://elasticsearch:9200
    networks:
      local:
        aliases:
          - kibana

  elasticsearch:
    container_name: elasticsearch 
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.1
    volumes: 
     - "esdata:/usr/share/elasticsearch/data"
     - ${ENV_ES_CONF_DIR}/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    expose:
      - "9200"
    environment:
      discovery.type: "single-node"
    networks:
      local:
        aliases:
          - elasticsearch

  fluentd:
    container_name: fluentd
    build: ./fluentd
    volumes:
      - ${ENV_FLUENTD_CONF_DIR}:/fluentd/etc
      - ${ENV_FLUENTD_LOG_DIR}:/logs
    ports:
      - "24224:24224"
    networks:
      local:
        aliases:
          - fluentd

volumes:
  esdata:
  mongodbdata:

networks:
  local:
    driver: bridge
    ipam:
      driver: default
      config:
        - 
          subnet: 10.3.0.0/16
