version: "3.5"
services:

  enterprise-search:
    image: docker.elastic.co/enterprise-search/enterprise-search:8.0.0
    volumes:
      - es-config:/usr/share/enterprise-search/es-config
    ports:
      - 3002:3002
    environment:
      secret_management.encryption_keys: '[2f983d978dfb257aaa0586ea2fae8f2c60feac14c34bb6cb3ef2af355dce1192]'
      allow_es_settings_modification: 'true'
      elasticsearch.host: http://elasticsearch:9200
      #elasticsearch.username: elastic
      #elasticsearch.password: exLUqEk9Ex39WBnF 
      elasticsearch.ssl.enabled: 'false'
      elasticsearch.ssl.certificate_authority: /usr/share/enterprise-search/es-config/certs/http_ca.crt
      kibana.external_url: http://kibana:5601
    networks:
      local:
        aliases:
          - enterprise-search

  pegasus-spring:
    container_name: pegasus-spring
    image: ${ENV_PEGASUS_CONTAINER} 
    depends_on: 
      - mariadb
    ports:
      - "${ENV_APACHE_TOMCAT_PORT:-3030}:3030"
    environment:
      SPRING_BOOT_ENVIRONMENT: ${ENV_DOCKER_ENVIRONMENT}
      MYSQL_HOST: ${ENV_MYSQL_HOST}
      MYSQL_USER: ${ENV_MYSQL_USER}
      MYSQL_PASSWORD: ${ENV_MYSQL_PASSWORD}
      TZ: "America/Detroit"
    privileged: true
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "${ENV_FLUENTD_ADDRESS}"
        tag: "pegasus-data"
    networks:
      local:
        aliases:
          - pegasus-spring
          
  hubble-spring:
    container_name: hubble-spring
    image: ${ENV_HUBBLE_CONTAINER} 
    depends_on: 
      - mariadb
    ports:
      - "3040:3030"
    environment:
      SPRING_BOOT_ENVIRONMENT: ${ENV_DOCKER_ENVIRONMENT}
      MYSQL_HOST: ${ENV_MYSQL_HOST}
      MYSQL_USER: ${ENV_MYSQL_USER}
      MYSQL_PASSWORD: ${ENV_MYSQL_PASSWORD}
      TZ: "America/Detroit"
    privileged: true
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "${ENV_FLUENTD_ADDRESS}"
        tag: "hubble-data"
    networks:
      local:
        aliases:
          - hubble-spring          

  mariadb:
    container_name: mariadb
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${ENV_MYSQL_PASSWORD}
    volumes:
      - mariadbdata:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      local:
        aliases:
          - mariadb
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    environment:
      TZ: "America/Detroit"
    ports:
      - 9090:8080 
    networks:
      local:
        aliases:
          - adminer
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    container_name: es01
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - esdata01:/usr/share/elasticsearch/data
      - ${ENV_ES_CONF_DIR}/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      - node.name=es01
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "TZ=America/Detroit"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: always
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "${ENV_FLUENTD_ADDRESS}"
        tag: "ke-es01"
    networks:
      local:
        aliases:
          - elasticsearch

  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    container_name: es02
    expose:
      - 9200
      - 9300
    volumes:
      - esdata02:/usr/share/elasticsearch/data
      - ${ENV_ES_CONF_DIR}/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      - node.name=es02
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "TZ=America/Detroit"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: always
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "${ENV_FLUENTD_ADDRESS}"
        tag: "ke-es02"
    networks:
      local:
        aliases:
          - elasticsearch

  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    container_name: es03
    expose:
      - 9200
      - 9300
    volumes:
      - esdata03:/usr/share/elasticsearch/data
      - ${ENV_ES_CONF_DIR}/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      - node.name=es03
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "TZ=America/Detroit"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: always
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "${ENV_FLUENTD_ADDRESS}"
        tag: "ke-es03"
    networks:
      local:
        aliases:
          - elasticsearch

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.16.1
    ports:
      - 5601:5601
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "10"
    depends_on:
      - es01
      - es02
      - es03
    environment:
      SERVER_NAME: elasticsearch
      ELASTICSEARCH_URL: http://elasticsearch:9200
      LOGGING_QUIET: "true"
      TZ: "America/Detroit"
      ENTERPRISESEARCH_HOST: http://enterprise-search:3002
    volumes:
      - ${ENV_KIBANA_CONF_DIR}/kibana.yml:/usr/share/kibana/kibana.yml
    networks:
      local:
        aliases:
          - kibana

  atlas-file-service:
    container_name: atlas-file-service
    image: kingstonduo/atlas-file-service:3.1
    ports:
      - "5000:5000"
    volumes:
      - ${ENV_FLASK_HOME}:/code
    environment:
      - FLASK_ENV=production
      - MINIO_ACCESS_KEY=${ENV_MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${ENV_MINIO_SECRET_KEY}
      - MINIO_URL=${ENV_MINIO_URL}
      - BUCKET_NAME=${ENV_BUCKET_NAME}
      - "TZ=America/Detroit"
    networks:
      local:
        aliases:
          - atlas-file-service   
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "${ENV_FLUENTD_ADDRESS}"
        tag: "atlas-file-service"

  minio-s3:
    container_name: minio
    image: minio/minio
    ports:
      - "9000:9000"
    environment:
      - MINIO_ACCESS_KEY=${ENV_MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${ENV_MINIO_SECRET_KEY}
      - "TZ=America/Detroit"
    command: gateway s3
    networks:
      local:
        aliases:
          - minio-s3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  arranger-server:
    image: overture/arranger-server:2.16.1
    container_name: arranger-server.local
    depends_on:
      - es01
      - es02
      - es03
    ports:
      - 5050:5050
    environment:
      ES_HOST: http://elasticsearch:9200
      TZ: "America/Detroit"
    networks:
      local:
        aliases:
          - arranger-server
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

volumes:
  es-config:
    driver: local
  esdata01:
    driver: local
  esdata02:
    driver: local
  esdata03:
    driver: local
  mariadbdata:

networks:
  local:
    name: dataPortal
    ipam:
      driver: default
      config:
        - 
          subnet: 10.12.0.0/16
