version: "3.5"
services:

  pegasus-spring:
    container_name: pegasus-spring
    image: ${ENV_PEGASUS_CONTAINER}
    depends_on: 
      - mariadb
    ports:
      - "${ENV_APACHE_TOMCAT_PORT:-3030}:3030"
    environment:
      SPRING_BOOT_ENVIRONMENT: ${ENV_DOCKER_ENVIRONMENT}
      MYSQL_HOST: ${ENV_MYSQL_HOST}
      MYSQL_USER: ${ENV_MYSQL_USER}
      MYSQL_PASSWORD: ${ENV_MYSQL_PASSWORD}
      TZ: "America/Detroit"
    privileged: true
    networks:
      local:
        aliases:
          - pegasus-spring
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
  
  hubble-spring:
    container_name: hubble-spring
    image: ${ENV_HUBBLE_CONTAINER}
    depends_on: 
      - mariadb
    ports:
      - "3040:3030"
    environment:
      SPRING_BOOT_ENVIRONMENT: ${ENV_DOCKER_ENVIRONMENT}
      MYSQL_HOST: ${ENV_MYSQL_HOST}
      MYSQL_USER: ${ENV_MYSQL_USER}
      MYSQL_PASSWORD: ${ENV_MYSQL_PASSWORD}
      RECENTLY_RELEASED_DATE: ${RECENTLY_RELEASED_DATE}
      TZ: "America/Detroit"
    privileged: true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    networks:
      local:
        aliases:
          - hubble-spring       

  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${ENV_MYSQL_PASSWORD}
    volumes:
      - mariadbdata:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      local:
        aliases:
          - mariadb
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  adminer:
    image: adminer
    restart: always
    environment:
      - "TZ=America/Detroit"
    ports:
      - 9090:8080 
    networks:
      local:
        aliases:
          - adminer    
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
          
  atlas-file-service:
    image: kingstonduo/atlas-file-service:3.3
    depends_on: 
      - mariadb    
    ports:
      - "5000:5000"
    volumes:
      - ${ENV_FLASK_HOME}:/code
    environment:
      - FLASK_ENV=production
      - MINIO_ACCESS_KEY=${ENV_MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${ENV_MINIO_SECRET_KEY}
      - MINIO_URL=${ENV_MINIO_URL}
      - BUCKET_NAME=${ENV_BUCKET_NAME}
      - MYSQL_HOST=${ENV_MYSQL_HOST}
      - MYSQL_USER=${ENV_MYSQL_USER}
      - MYSQL_PASSWORD=${ENV_MYSQL_PASSWORD}
      - TZ=America/Detroit
    networks:
      local:
        aliases:
          - atlas-file-service   
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
 
  minio-s3:
    image: minio/minio
    ports:
      - "9000:9000"
    environment:
      - MINIO_ACCESS_KEY=${ENV_MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${ENV_MINIO_SECRET_KEY}
      - "TZ=America/Detroit"
    command: gateway s3
    networks:
      local:
        aliases:
          - minio-s3    
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

volumes:
  esdata01:
    driver: local
  esdata02:
    driver: local
  esdata03:
    driver: local
  mariadbdata:

networks:
  local:
    name: dataPortal
    ipam:
      driver: default
      config:
        - 
          subnet: 10.12.0.0/16
