version: "3.5"
services:

  arranger-ui:
    image: overture/arranger-ui:2.16.1
    hostname: arranger-ui.local
    container_name: arranger-ui.local
    environment:
      - "TZ=America/Detroit"
      - "REACT_APP_ARRANGER_ADMIN_ROOT=http://arranger-server:5050"
    ports:
      - 8080:3000
      - 8081:3000
    networks:
      local:
        aliases:
          - arranger-ui
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
        
networks:
  local:
    name: dataPortal