version: "3.5"
services:

  index-creation-worker:
    image: ${ENV_INDEX_CREATION_WORKER}
    container_name: index-creation-worker
    restart: always
    ports:
      - "5001:5000"
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: ${ENV_MYSQL_PASSWORD}
      MYSQL_HOST: ${ENV_MYSQL_HOST}
      TZ: "America/Detroit"
    networks:
      local:
        aliases:
          - index-creator
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

networks:
  local:
    name: dataPortal
