version: "3"
services:

  state-spring:
    container_name: state-spring
    image: kingstonduo/state-manager-service:latest
    volumes:
      - "${ENV_DATALAKE_FILE_DIR}:/data"    
    ports:
      - "${ENV_APACHE_TOMCAT_PORT:-3060}:3060"
    environment:
      SPRING_BOOT_ENVIRONMENT: ${ENV_DOCKER_ENVIRONMENT}
    privileged: true
    networks:
      dataLake:
        aliases:
          - state-spring

volumes:
  esdata:

networks:
  dataLake:
    external: true
