version: "3"
services:

  spring:
    container_name: scutum-spring
    image: kingstonduo/kpmp-spring
    volumes:
      - "${ENV_SPRING_BOOT_APPDIR}:/home/gradle"
    environment:
      SPRING_BOOT_ENVIRONMENT: ${ENV_DOCKER_ENVIRONMENT}
      DEFAULT_CLIENT_ID: ${ENV_DEFAULT_CLIENT_ID}
    privileged: true
    networks:
      dataLake:
        aliases:
          - scutum-spring

networks:
  dataLake:
    external: true
