version: "3"
services:

  apache:
    container_name: delphinus-apache
    image: ${ENV_APACHE_CONTAINER} 
    ports:
      - "80:80"
      - "443:443"
    environment:
      - ENV_APACHE_SERVER_NAME=${ENV_APACHE_SERVER_NAME}
    volumes:
      - ${ENV_REACT_BASE_APPDIR}/build:/var/www/html/landing
      - ${ENV_REACT_DEMO_APPDIR_ONE}/build:/var/www/html/dpr
      - ${ENV_REACT_DEMO_APPDIR_TWO}/build:/var/www/html/atlas
      - ${ENV_SSL_CERT_DIR}:/certs
      - ${ENV_SHIB_CONF_DIR}/shibboleth2.xml:/etc/shibboleth/shibboleth2.xml
      - ${ENV_WSI_FILES_DIR}:/data/deepZoomImages
      - ${ENV_WSI_ORIG_FILES_DIR}:/data/knowledgeEnvironment/deepZoom
      - ${ENV_APACHE_CONF_DIR}/delphinus.conf:/etc/httpd/conf.d/delphinus.conf
    networks:
      local:
        aliases:
          - delphinus-apache

  mongodb:
    container_name: delphinus-mongodb
    image: mongo:4.0
    environment:
       - MONGO_DATA_DIR=/data/db
       - MONGO_LOG_DIR=/dev/null
    volumes:
       - mongodbdata:/data/db 
    ports:
      - "127.0.0.1:${ENV_MONGO_PORT:-27017}:27017"
    command: mongod 
    networks:
      local:
        aliases:
          - delphinus-mongodb

  spring:
    container_name: delphinus-spring
    image: kingstonduo/kpmp-spring
    ports:
      - "${ENV_APACHE_TOMCAT_PORT:-3030}:3030"
    volumes:
      - "${ENV_SPRING_BOOT_APPDIR}:/home/gradle"
    environment:
      SPRING_BOOT_ENVIRONMENT: ${ENV_DOCKER_ENVIRONMENT}
    privileged: true
    networks:
      local:
        aliases:
          - delphinus-spring

volumes:
  mongodbdata:

networks:
  local:
    driver: bridge
    ipam:
      driver: default
      config:
        - 
          subnet: 10.3.0.0/16
