version: "3"
services:

  user-auth:
    container_name: user-auth
    image: ${ENV_AUTH_IMAGE} 
    environment:
      DEFAULT_CLIENT_ID: ${ENV_DEFAULT_CLIENT_ID}
    privileged: true
    networks:
      local:
        aliases:
          - user-auth

  apache:
    container_name: delphinus-apache
    image: ${ENV_APACHE_CONTAINER} 
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${ENV_DPR_REACT_APPDIR}/build:/var/www/html/dpr
      - ${ENV_PP_REACT_APPDIR}/build:/var/www/html/pp
      - ${ENV_SSL_CERT_DIR}:/certs
      - ${ENV_SHIB_CONF_DIR}/shibboleth2.xml:/etc/shibboleth/shibboleth2.xml
      - ${ENV_WSI_FILES_DIR}:/data/deepZoomImages
      - ${ENV_WSI_ORIG_FILES_DIR}:/data/knowledgeEnvironment/deepZoom
      - ${ENV_APACHE_CONF_DIR}/delphinus.conf:/etc/apache2/conf-enabled/delphinus.conf        
    networks:
      local:
        aliases:
          - delphinus-apache

  mongodb:
    container_name: delphinus-mongodb
    image: mongo:4.0
    environment:
       - MONGO_DATA_DIR=/data/db
       - MONGO_LOG_DIR=/dev/null
    volumes:
       - mongodbdata:/data/db 
    ports:
      - "127.0.0.1:${ENV_MONGO_PORT:-27017}:27017"
    command: mongod 
    networks:
      local:
        aliases:
          - delphinus-mongodb

  spring:
    container_name: delphinus-spring
    image: ${ENV_DPR_IMAGE}
    ports:
      - "${ENV_APACHE_TOMCAT_PORT:-3030}:3030"
    environment:
      SPRING_BOOT_ENVIRONMENT: ${ENV_DOCKER_ENVIRONMENT}
      CLIENT_ID: ${ENV_CLIENT_ID}
    privileged: true
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "${ENV_FLUENTD_ADDRESS}"
        tag: "delphinus-data"    
    networks:
      local:
        aliases:
          - delphinus-spring


  cassie-spring:
    container_name: cassie-spring
    image: ${ENV_PP_IMAGE}
    environment:
      - "TZ=America/Detroit"
    ports:
      - "${ENV_PP_PORT:-3060}:3030"
    environment:
      SPRING_BOOT_ENVIRONMENT: ${ENV_DOCKER_ENVIRONMENT}
    privileged: true
    networks:
      local:
        aliases:
          - cassie-spring
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "${ENV_FLUENTD_ADDRESS}"
        tag: cassie-data


volumes:
  mongodbdata:

networks:
  local:
    driver: bridge
    ipam:
      driver: default
      config:
        - 
          subnet: 10.3.0.0/16
