version: "3"
services:

  apache:
    container_name: libra-apache
    image: ${ENV_APACHE_CONTAINER} 
    ports:
      - "80:80"
      - "443:443"
    environment:
      - ENV_APACHE_SERVER_NAME=${ENV_APACHE_SERVER_NAME}
    volumes:
      - ${ENV_REACT_APPDIR}/build:/var/www/html
      - ${ENV_SSL_CERT_DIR}:/certs
      - ${ENV_SHIB_CONF_DIR}/shibboleth2.xml:/etc/shibboleth/shibboleth2.xml
    networks:
      dataLake:
        aliases:
          - libra-apache

volumes:
  esdata:

networks:
  dataLake:
    external: true
