version: "3"
services:

  spring:
    container_name: libra_spring
    image: kingstonduo/kpmp-spring
    ports:
      - "${ENV_APACHE_TOMCAT_PORT:-3040}:3040"
    volumes:
      - "${ENV_SPRING_BOOT_APPDIR}:/home/gradle"
    environment:
      SPRING_BOOT_ENVIRONMENT: ${ENV_DOCKER_ENVIRONMENT}
    privileged: true
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "localhost:24224"
        tag: "libra-data"
    networks:
      orion_local:
        aliases:
          - spring

  postfix:
    container_name: postfix_relay
    image: juanluisbaptiste/postfix:latest
    expose:
      - 25
    environment:
      SMTP_SERVER: smtp.gmail.com
      SMTP_USERNAME: kpmpNotifications@gmail.com 
      SMTP_PASSWORD: lcbzgrkijgtmaiqn 
      SERVER_HOSTNAME: fqdn.example.com 
    networks:
      orion_local:
        aliases:
          - postfix

volumes:
  esdata:

networks:
  orion_local:
    external: true
