version: "3"
services:

  spring:
    container_name: libra_spring
    image: kingstonduo/kpmp-spring
    ports:
      - "${ENV_APACHE_TOMCAT_PORT:-3040}:3040"
    volumes:
      - "${ENV_SPRING_BOOT_APPDIR}:/home/gradle"
    environment:
      SPRING_BOOT_ENVIRONMENT: ${ENV_DOCKER_ENVIRONMENT}
    privileged: true
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "localhost:24224"
        tag: "libra-data"
    networks:
      orion_local:
        aliases:
          - spring

volumes:
  esdata:
  mongodbdata:

networks:
  orion_local:
    external: true
