version: "3"
services:

  apache:
    container_name: libra-apache
    image: ${ENV_APACHE_CONTAINER} 
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      - ENV_APACHE_SERVER_NAME=${ENV_APACHE_SERVER_NAME}
    volumes:
      - ${ENV_REACT_APPDIR}/build:/var/www/html
      - ${ENV_SSL_CERT_DIR}:/certs
      - ${ENV_SHIB_CONF_DIR}/shibboleth2.xml:/etc/shibboleth/shibboleth2.xml
    networks:
      dataLake:
        aliases:
          - libra-apache

  spring:
    container_name: libra-spring
    image: kingstonduo/kpmp-spring
    ports:
      - "${ENV_APACHE_TOMCAT_PORT:-3050}:3050"
    volumes:
      - "${ENV_SPRING_BOOT_APPDIR}:/home/gradle"
    environment:
      SPRING_BOOT_ENVIRONMENT: ${ENV_DOCKER_ENVIRONMENT}
    privileged: true
#    logging:
#      driver: "fluentd"
#      options:
#        fluentd-address: "localhost:24224"
#        tag: "orion-data"
    networks:
      dataLake:
        aliases:
          - libra-spring

volumes:
  esdata:

networks:
  dataLake:
    external: true
