version: "3"
services:

  libra-spring:
    container_name: libra-spring
    image: kingstonduo/kpmp-spring
    ports:
      - "${ENV_APACHE_TOMCAT_PORT:-3050}:3050"
    volumes:
      - "${ENV_SPRING_BOOT_APPDIR}:/home/gradle"
    environment:
      SPRING_BOOT_ENVIRONMENT: ${ENV_DOCKER_ENVIRONMENT}
    privileged: true
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "localhost:24224"
        tag: "libra-data"
    networks:
      dataLake:
        aliases:
          - libra-spring

volumes:
  esdata:

networks:
  dataLake:
    external: true
