version: "3"
services:

  data-manager-service:
    container_name: data-manager-service
    image: ${ENV_DMD_SERVICE_CONTAINER}
    restart: unless-stopped
    expose:
      - 5000
    environment:
      - mysql_user=${mysql_user}
      - mysql_pwd=${mysql_pwd}
      - mysql_host=${mysql_host}
      - mysql_port=${mysql_port}
      - mysql_db=${mysql_db}
      - mongo_host=${mongo_host}
      - mongo_port=${mongo_port}
      - mongo_db=${mongo_db}
      - spectrack_token=${spectrack_token}
      - spectrack_base_url=${spectrack_base_url}
      - dlu_hostname_with_underscores=${DLU_HOSTNAME_WITH_UNDERSCORES}
    mem_limit: 6g
    volumes:
      - "${ENV_DATALAKE_FILE_DIR}:/data"
      - "${ENV_GLOBUS_FILE_MOUNT}:/globus"      
    networks:
      dataLake:
        aliases:
          - data-manager-service

  dlu-watcher-service:
      container_name: dlu-watcher
      image: ${ENV_DLU_WATCHER_CONTAINER}
      user: ${dlu_user}:${dlu_group}
      environment:
        - mysql_user=${mysql_user}
        - mysql_pwd=${mysql_pwd}
        - mysql_host=${mysql_host}
        - mysql_port=${mysql_port}
        - mysql_db=${mysql_db}
        - mongo_host=${mongo_host}
        - mongo_port=${mongo_port}
        - mongo_db=${mongo_db}
        - spectrack_token=${spectrack_token}
        - spectrack_base_url=${spectrack_base_url}
        - INSIDE_DOCKER=${INSIDE_DOCKER}
        - dlu_user=${dlu_user}
        - dlu_group=${dlu_group}
        - dlu_hostname_with_underscores=${DLU_HOSTNAME_WITH_UNDERSCORES}
        - slack_passcode=${slack_passcode}
      volumes:
        - "${ENV_DATALAKE_FILE_DIR}:/data"
        - "${ENV_GLOBUS_FILE_MOUNT}:/globus"   
        - /etc/passwd:/etc/passwd:ro
        - /etc/group:/etc/group:ro 
      networks:
        dataLake:


networks:
  dataLake:
    external: true
