version: "3"
services:

  apache:
    container_name: circinus-apache
    image: ${ENV_APACHE_CONTAINER} 
    ports:
      - "80:80"
      - "443:443"
    environment:
      - ENV_APACHE_SERVER_NAME=${ENV_APACHE_SERVER_NAME}
    volumes:
      - ${ENV_REACT_BASE_APPDIR}/build:/var/www/html/landing
      - ${ENV_REACT_DEMO_APPDIR_ONE}/build:/var/www/html/dpr
      - ${ENV_REACT_DEMO_APPDIR_TWO}/build:/var/www/html/atlas
      - ${ENV_SSL_CERT_DIR}:/certs
      - ${ENV_SHIB_CONF_DIR}/shibboleth2.xml:/etc/shibboleth/shibboleth2.xml
      - ${ENV_WSI_FILES_DIR}:/data/deepZoomImages
      - ${ENV_WSI_ORIG_FILES_DIR}:/data/knowledgeEnvironment/deepZoom
      - ${ENV_APACHE_CONF_DIR}/circinus.conf:/etc/httpd/conf.d/circinus.conf
    networks:
      local:
        aliases:
          - circinus-apache

networks:
  local:
    driver: bridge
    ipam:
      driver: default
      config:
        - 
          subnet: 10.3.0.0/16
