version: "3.5"
services:

# NOTE: Depends on Knowledge Environment services.

  apache:
    container_name: repository-apache
    image: ${ENV_APACHE_CONTAINER} 
    ports:
      - "80:80"
      - "443:443"
    environment:
      - ENV_APACHE_SERVER_NAME=${ENV_APACHE_SERVER_NAME}
      - ENV_ARRANGER_SERVER_ADDRESS=${ENV_ARRANGER_SERVER_ADDRESS}
      - ENV_FILE_SERVER_ADDRESS=${ENV_FILE_SERVER_ADDRESS}
      - ENV_EXPLORER_DATA_SERVER_ADDRESS=${ENV_EXPLORER_DATA_SERVER_ADDRESS}
      - "TZ=America/Detroit"
    volumes:
      - ${ENV_REACT_APPDIR}/build:/var/www/html
      - ${ENV_REPOSITORY_APPDIR}/build:/var/www/html/repository
      - ${ENV_EXPLORER_REACT_APPDIR}/build:/var/www/html/explorer
      - ${ENV_REPOSITORY_REPLACEMENT_APPDIR}/build:/var/www/html/repository2
      - ${ENV_SPATIAL_APPDIR}/build:/var/www/html/spatial-viewer
      - ${ENV_SSL_CERT_DIR}:/certs
    networks:
      local:
        aliases:
          - apache
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

networks:
  local:
    name: dataPortal
    ipam:
      driver: default
      config:
        - 
          subnet: 10.12.0.0/16
