version: "3.5"
services:

# NOTE: Depends on Knowledge Environment services.

  apache:
    container_name: repository-apache
    image: ${ENV_APACHE_CONTAINER} 
    ports:
      - "80:80"
      - "443:443"
    environment:
      - ENV_APACHE_SERVER_NAME=${ENV_APACHE_SERVER_NAME}
      - ENV_ARRANGER_SERVER_ADDRESS=${ENV_ARRANGER_SERVER_ADDRESS}
      - ENV_FILE_SERVER_ADDRESS=${ENV_FILE_SERVER_ADDRESS}
    volumes:
      - ${ENV_REACT_APPDIR}/build:/var/www/html
      - ${ENV_REPOSITORY_APPDIR}/build:/var/www/html/repository
      - ${ENV_EXPLORER_REACT_APPDIR}/build:/var/www/html/explorer
      - ${ENV_SSL_CERT_DIR}:/certs
    networks:
      local:
        aliases:
          - apache

  index-creation-worker:
    image: ${ENV_INDEX_CREATION_WORKER}
    container_name: index-creation-worker
    restart: always
    ports:
      - "5001:5000"
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: ${ENV_MARIADB_ROOT_PWD}
    networks:
      local:
        aliases:
          - index-creator

networks:
  local:
    name: dataPortal
    ipam:
      driver: default
      config:
        - 
          subnet: 10.12.0.0/16
