version: "3"
services:

  apache:
    container_name: cassie-apache
    image: ${ENV_APACHE_CONTAINER} 
    ports:
      - "80:80"
      - "443:443"
    environment:
      - ENV_APACHE_SERVER_NAME=${ENV_APACHE_SERVER_NAME}
    volumes:
      - ${ENV_REACT_APPDIR}/build:/var/www/html
      - ${ENV_SSL_CERT_DIR}:/certs
      - ${ENV_WSI_FILES_DIR}:/data/deepZoomImages
      - ${ENV_WSI_ORIG_FILES_DIR}:/data/knowledgeEnvironment/deepZoom
      - ${ENV_APACHE_CONF_DIR}/cassiopeia.conf:/etc/httpd/conf.d/cassiopeia.conf
    networks:
      local:
        aliases:
          - cassie-apache
    

  mongodb:
    container_name: delphinus-mongodb
    image: mongo:4.0
    environment:
       - MONGO_DATA_DIR=/data/db
       - MONGO_LOG_DIR=/dev/null
    volumes:
       - mongodbdata:/data/db 
    ports:
      - "127.0.0.1:${ENV_MONGO_PORT:-27017}:27017"
    command: mongod 
    networks:
      local:
        aliases:
          - delphinus-mongodb

  spring:
    container_name: cassie-spring
    image: ${ENV_SPRING_BOOT_CONTAINER}
    environment:
      - "TZ=America/Detroit"
    ports:
      - "${ENV_APACHE_TOMCAT_PORT:-3030}:3030"
    volumes:
      - "${ENV_SPRING_BOOT_APPDIR}:/home/gradle"
    environment:
      SPRING_BOOT_ENVIRONMENT: ${ENV_DOCKER_ENVIRONMENT}
    privileged: true
    networks:
      local:
        aliases:
          - cassie-spring
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "${ENV_FLUENTD_ADDRESS}"
        tag: cassie-data

volumes:
  mongodbdata:

networks:
  local:
    driver: bridge
    ipam:
      driver: default
      config:
        - 
          subnet: 10.2.0.0/16
