version: "3"
services:

  spring:
    container_name: eridanus-spring
    image: kingstonduo/eridanus-data:1.1
    restart: unless-stopped    
    environment:
      SPRING_BOOT_ENVIRONMENT: ${ENV_DOCKER_ENVIRONMENT}
    ports:
      - "${ENV_APACHE_TOMCAT_PORT:-3040}:3040"
    privileged: true
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "${ENV_FLUENTD_ADDRESS}"
        tag: "eridanus-data"
    networks:
      dataLake:
        aliases:
          - eridanus-spring

  postfix:
    container_name: postfix-relay
    image: juanluisbaptiste/postfix:latest
    restart: unless-stopped
    expose:
      - 25
    environment:
      SMTP_SERVER: ${ENV_SMTP_SERVER}
      SMTP_USERNAME: ${ENV_SMTP_USERNAME} 
      SMTP_PASSWORD: ${ENV_SMTP_PASSWORD}
      SERVER_HOSTNAME: ${ENV_SMTP_HOST}
    networks:
      dataLake:
        aliases:
          - postfix

  mariadb:
    container_name: eridanus-mariadb
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${ENV_MYSQL_PASSWORD}
    volumes:
      - mariadbdata:/var/lib/mysql
    ports:
      - 3307:3306
    networks:
      dataLake:
        aliases:
          - mariadb
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  adminer:
    container_name: eridanus-adminer
    image: adminer
    restart: always
    environment:
      TZ: "America/Detroit"
    ports:
      - 9090:8080 
    networks:
      dataLake:
        aliases:
          - adminer
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

volumes:
  esdata:
  mariadbdata:

networks:
  dataLake:
    external: true
