version: "3.5"
services:

  apache:
    container_name: apache-proxy
    image: kingstonduo/apache:apache-dl-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${ENV_UPLOADER_BASE_DIR}/build:/var/www/html/upload
      - ${ENV_CURATION_BASE_DIR}/build:/var/www/html/curation
      - ${ENV_SSL_CERT_DIR}:/certs
      - ${ENV_SHIB_CONF_DIR}/shibboleth2.xml:/etc/shibboleth/shibboleth2.xml
    networks:
      local:
        aliases:
          - apache

volumes:
  esdata:

networks:
  local:
    name: dataLake
    driver: bridge
    ipam:
      driver: default
      config:
        - 
          subnet: 10.10.0.0/16
