version: "3"
services:

  apache:
    container_name: microscopium-apache
    image: ${ENV_APACHE_CONTAINER} 
    ports:
      - "80:80"
      - "443:443"
    environment:
      - ENV_APACHE_SERVER_NAME=${ENV_APACHE_SERVER_NAME}
    volumes:
      - ${ENV_REACT_APPDIR}/build:/var/www/html
      - ${ENV_SSL_CERT_DIR}:/certs
      - ${ENV_APACHE_CONF_DIR}/microscopium.conf:/etc/httpd/conf.d/microscopium.conf
    networks:
      local:
        aliases:
          - microscopium-apache

networks:
  local:
    driver: bridge
    ipam:
      driver: default
      config:
        - 
          subnet: 10.2.0.0/16
